[package]
name = "codeuchain"
version = "0.1.0"
edition = "2021"
description = "CodeUChain Rust: Agape-Optimized Implementation"
license = "MIT"
repository = "https://github.com/joshuawink/codeuchain"
keywords = ["chain", "middleware", "async", "processing"]
categories = ["asynchronous", "data-structures"]

[dependencies]
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
async-trait = "0.1"
anyhow = "1.0"

[dev-dependencies]
tokio-test = "0.4"